### ISSUE TITLE
Pubsub Client call back error

### ISSUE THREAD

**Issue by clebarron** [openhomeautomation/adafruit-io-dashboard#3]
I have tried compiling in linux and windows and each throws roughly the same error.
Arduino: 1.6.7 (Windows 10), Board: "Arduino/Genuino Uno"

adafruit_io_sensors:40: error: 'callback' was not declared in this scope

 PubSubClient mqttclient("io.adafruit.com", 1883, callback, client);

```
                                              ^
```

exit status 1
'callback' was not declared in this scope

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
its always in the call back client, most recent libraries are installed, also tried other suggestions from older issue.still no go.

**Comment by marcoschwartz** [comment]
Fixed :) It was simply an error due the latest Arduino IDE.
